# Changes here will be overwritten by Copier
_commit: v2.0.7
_src_path: gh:lincc-frameworks/python-project-template
author_email: fberlfei@andrew.cmu.edu
author_name: Roman-HLIS-Cosmology-PIT
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: false
mypy_type_checking: none
package_name: metadetect_driver
project_license: none
project_name: metadetect-driver
project_organization: Roman-HLIS-Cosmology-PIT
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: none
