[project]
name = "metadetect_driver"
version = "0.1"
description = "Driver package to run metadetecion"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Your Name", email = "you@example.com"  }
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/Roman-HLIS-Cosmology-PIT/metadetect-driver"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
