from pathlib import Path

import pyarrow.parquet as pq
import pytest
from pandas.testing import assert_frame_equal
from pyimcom.analysis import OutImage

import metadetect_driver


def test_reproducability():
    """
    Test that the metadetect driver produces the same output for the same input.
     This is a regression test to ensure that changes to the code do not change the output.
     The output catalogs are generated by the `main` function in `tests/write_output.py`,
    """
    image_paths = [
        str(Path(__file__).parent / "data" / "H158" / "output_00_00.fits"),
        str(Path(__file__).parent / "data" / "J129" / "output_00_00.fits"),
    ]
    outimages = [OutImage(image_path) for image_path in image_paths]

    results = metadetect_driver.run_metadetect(outimages)

    output_path = Path(__file__).parent / "output"

    for shear_type, result in results.items():
        expected = pq.read_table(output_path / f"metadetect_catalog_{shear_type}.parquet")

        # NOTE this does _not_ require that the metadata be equal, so this will
        # not raise an error even if there is a version mismatch between
        # packages recorded in the metadata
        assert result.schema == expected.schema

        # NOTE we use pandas to check equality because of nan handling.
        # This is not ideal.
        assert_frame_equal(result.to_pandas(), expected.to_pandas())


def test_valid():
    """
    Test that the metadetect driver runs without errors for valid input.
     This is a regression test to ensure that changes to the code do not break the driver.
     The output catalogs are generated by the `main` function in `tests/write_output.py`,
    """
    with pytest.raises(Exception):  # noqa
        image_paths = [
            str(Path(__file__).parent / "data" / "H158" / "output_00_00.fits"),
            str(Path(__file__).parent / "data" / "H158" / "output_00_00.fits"),
        ]
        outimages = [OutImage(image_path) for image_path in image_paths]

        metadetect_driver.run_metadetect(outimages)

    with pytest.raises(Exception):  # noqa
        image_paths = [
            str(Path(__file__).parent / "data" / "H158" / "output_00_00.fits"),
            str(Path(__file__).parent / "data" / "H158" / "output_00_01.fits"),
        ]
        outimages = [OutImage(image_path) for image_path in image_paths]

        metadetect_driver.run_metadetect(outimages)

    with pytest.raises(Exception):  # noqa
        image_paths = [
            str(Path(__file__).parent / "data" / "H158" / "output_00_00.fits"),
            str(Path(__file__).parent / "data" / "J129" / "output_00_01.fits"),
        ]
        outimages = [OutImage(image_path) for image_path in image_paths]

        metadetect_driver.run_metadetect(outimages)
