# Size of the taget Gaussian PSF in IMCOM
PSF_FWHM:
    Y106: 0.22
    J129: 0.231
    H158: 0.242
    F184: 0.253
    K213: 0.264

# Size of the image used to draw the PSF
PSF_IMG_SIZE: 151

# Size of one IMCOM block
IMG_SIZE: 2688
# Boundary used to avoid edge effects
# Objects for which the centre is within this distance from the edge will be
# masked out.
BOUND_SIZE: 100

METADETECT_CONFIG:
    # Shape measurement method
    # wmom: weighted moments
    model: wmom

    # Size of the weight function for the moments
    weight:
        fwhm: 1.2  # arcsec

    # Metacal settings
    metacal:
        psf: fitgauss
        # Kind of shear applied to the image
        types: [noshear, 1p, 1m, 2p, 2m]

    sx:
        # in sky sigma
        # DETECT_THRESH
        detect_thresh: 10.

        # Minimum contrast parameter for deblending
        # DEBLEND_MINCONT
        deblend_cont: 0.00001

        # minimum number of pixels above threshold
        # DETECT_MINAREA: 6
        minarea: 4

        filter_type: conv

        # 7x7 convolution mask of a gaussian PSF with FWHM = 3.0 pixels.
        filter_kernel: [
            [0.004963, 0.021388, 0.051328, 0.068707, 0.051328, 0.021388, 0.004963],  # noqa
            [0.021388, 0.092163, 0.221178, 0.296069, 0.221178, 0.092163, 0.021388],  # noqa
            [0.051328, 0.221178, 0.530797, 0.710525, 0.530797, 0.221178, 0.051328],  # noqa
            [0.068707, 0.296069, 0.710525, 0.951108, 0.710525, 0.296069, 0.068707],  # noqa
            [0.051328, 0.221178, 0.530797, 0.710525, 0.530797, 0.221178, 0.051328],  # noqa
            [0.021388, 0.092163, 0.221178, 0.296069, 0.221178, 0.092163, 0.021388],  # noqa
            [0.004963, 0.021388, 0.051328, 0.068707, 0.051328, 0.021388, 0.004963],  # noqa
        ]

    # This is for the cutout at each detection
    meds:
        min_box_size: 32
        max_box_size: 32

        box_type: iso_radius

        rad_min: 4
        rad_fac: 2
        box_padding: 2

    # check for an edge hit
    bmask_flags: 2**30

    nodet_flags: 2**0