name: lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-name: docs
          environment-file: environment.yml
          cache-environment: true
          generate-run-shell: true

      - name: Install package and docs dependencies
        shell: micromamba-shell {0}
        run: |
          pip install -e ".[docs]"

      - name: Run linter
        shell: micromamba-shell {0}
        run: ruff check src
