name: lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-name: metadetect-driver-lint
          create-args: >-
            python
            ruff
          generate-run-shell: true

      - name: Run linter
        shell: micromamba-shell {0}
        run: ruff check src
