name: test

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests

    strategy:
      matrix:
        pyver: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: ${{ matrix.pyver }}
      #     channels: conda-forge,defaults
      #     channel-priority: strict
      #     show-channel-urls: true
      #     miniforge-version: latest

      # - name: configure conda and install code
      #   shell: bash -l {0}
      #   run: |
      #     conda config --set always_yes yes
      #     conda install --quiet --yes --file requirements.txt
      #     conda install --quiet --yes --file requirements-dev.txt

      #     python -m pip install -e .

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .

      - name: Run pytest
        run: pytest --log-cli-level=INFO tests/
